VAR1=test1
VAR2=test2
VAR3=test3
VAR4=test4
VAR5=test5
VAR6=test6
VAR7=test7
VAR8=test8
VAR9=test9
VAR10=test10

all: dep1 dep2 dep3 dep4 dep5
	@echo All done

dep1:
	@echo dep1

dep2:
	@echo dep2

dep3:
	@echo dep3

dep4:
	@echo dep4

dep5:
	@echo dep5
